package com.True.Care.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.http.HttpStatus;
import org.springframework.dao.DataIntegrityViolationException;

import com.True.Care.modal.User;
import com.True.Care.repository.UserRepository;
import com.True.Care.util.Encryption;
import com.True.Care.util.JwtUtil;

@Controller // <-- Use this if you want JSON responses by default
@RequestMapping(path = "/") // This means URL's start with /demo (after Application pat)
public class UserController {

    @Autowired
    private Encryption encryption;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    Logger logger = LoggerFactory.getLogger(DepartmentsController.class);

    @PostMapping(path = "/register", consumes = "application/json")
    public ResponseEntity<String> addNewUser(@RequestBody User user) {
        try {
            userRepository.save(user);
            String email = user.getEmail();
            String encryptedEmail = encryption.encrypt(email);
            String token = jwtUtil.generateToken(encryptedEmail);
            return ResponseEntity.ok(token);
            // return ResponseEntity.ok("Saved");
        } catch (DataIntegrityViolationException e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Error: Email already exists.");
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Error: Something went wrong.");
        }
    }

    @GetMapping(path = "/user")
    public ResponseEntity<?> getLoggedInUser(@RequestHeader("Authorization") String authHeader) {
        try {
            // 1. Extract token from "Bearer <token>"
            if (authHeader == null || !authHeader.startsWith("Bearer ")) {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Missing or invalid Authorization header");
            }

            String token = authHeader.substring(7); // Remove "Bearer "

            // 2. Validate token and get encrypted email
            String encryptedEmail = jwtUtil.validateTokenAndRetrieveSubject(token);

            // 3. Decrypt email
            String email = encryption.decrypt(encryptedEmail);

            // 4. Find user by email
            User user = userRepository.findByEmail(email);
            if (user == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("User not found");
            }

            return ResponseEntity.ok(user);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token: " + e.getMessage());
        }
    }

    @Autowired
    private JwtUtil jwtUtil;

    @PostMapping(path = "/login", consumes = "application/json")
    public ResponseEntity<?> loginUser(@RequestBody User loginRequest) {
        User user = userRepository.findByEmail(loginRequest.getEmail());
        if (user == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body("User not found with email: " + loginRequest.getEmail());
        } else if (user.getPassword().equals(loginRequest.getPassword())) {
            try {
                String email = user.getEmail();
                String encryptedEmail = encryption.encrypt(email);
                String token = jwtUtil.generateToken(encryptedEmail);
                return ResponseEntity.ok(token);
            } catch (Exception e) {
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                        .body("Encryption error: " + e.getMessage());
            }
        } else {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid credentials");
        }
    }

}
